/**
 * Path: src/features/profile/info/ProfileVibeOptions.ts
 * Purpose: Shared selectable Likes, Dislikes, and Vibe Tag options.
 * Used by: ProfileVibeSection.
 */

export const VIBE_TAG_OPTIONS = [
  "Chill",
  "Romantic",
  "Funny",
  "Introvert",
  "Ambivert",
  "Extrovert",
  "Deep thinker",
  "Spontaneous",
  "Calm",
  "Chaotic good",
];

export const LIKE_OPTIONS = [
  "Coffee",
  "Tea",
  "Late-night talks",
  "Deep conversations",
  "Road trips",
  "Night drives",
  "Gym",
  "Yoga",
  "Meditation",
  "Running",
  "Dogs",
  "Cats",
  "Pets",
  "Sunsets",
  "Sunrises",
  "Beaches",
  "Mountains",
  "Nature walks",
  "Cooking",
  "Baking",
  "Trying new food",
  "Street food",
  "Music",
  "Live concerts",
  "Festivals",
  "Podcasts",
  "Audiobooks",
  "Movies",
  "TV shows",
  "Anime",
  "Gaming",
  "Board games",
  "Books",
  "Reading",
  "Writing",
  "Photography",
  "Travel",
  "Spontaneous plans",
  "Dancing",
  "Art",
  "Museums",
  "Minimalism",
  "Fashion",
  "Streetwear",
  "Perfumes",
  "Self-care",
  "Skincare",
  "Journaling",
  "Long walks",
  "Rainy days",
  "Honesty",
  "Kindness",
  "Ambition",
  "Stability",
  "Romance",
  "Surprises",
  "Spontaneity",
];

export const DISLIKE_OPTIONS = [
  "Smoking",
  "Drugs",
  "Dishonesty",
  "Lies",
  "Manipulation",
  "Gaslighting",
  "Cheating",
  "Ghosting",
  "Breadcrumbing",
  "Rudeness",
  "Arrogance",
  "Entitlement",
  "Judgmental people",
  "Closed mindset",
  "Negativity",
  "Drama",
  "Toxic behavior",
  "Disrespect",
  "Aggression",
  "Anger issues",
  "Passive aggression",
  "Loud chewing",
  "Bad hygiene",
  "Messiness",
  "Oversharing",
  "No boundaries",
  "Clinginess",
  "Jealousy",
  "Over-controlling",
  "Unreliability",
  "Inconsistency",
  "Excuses",
  "Victim mindset",
  "Laziness",
  "No ambition",
  "Lack of effort",
  "Late replies",
  "Dry texting",
  "No communication",
  "Overuse of phone",
  "Phone addiction",
  "Fake personas",
  "Attention seeking",
  "Disloyalty",
  "Public embarrassment",
  "Unkindness",
  "No accountability",
];