/**
 * ============================================================
 * 📁 File: src/config/rombuzzGifts.ts
 * 🎁 Purpose: Central frontend gift catalog for RomBuzz gifts.
 *
 * Used by:
 * - GiftPicker
 * - GiftCard
 * - GiftSummaryBar
 * - LetsBuzz posts/reels gift UI
 * - View Profile media gift UI
 * - Future chat/media gift UI
 *
 * Important:
 * - This file is for frontend display metadata only.
 * - Backend must still validate giftId and priceBC.
 * - App UI should show only gift image + BuzzCoin price.
 * - Gift names are internal/admin labels and should not be shown in the gift picker.
 * ============================================================
 */

export type RomBuzzGiftCategory =
  | "sweet"
  | "romantic"
  | "playful"
  | "premium"
  | "funny"
  | "attention"
  | "celebration"
  | "apology"
  | "exclusive"
  | "microbuzz"
  | "buzzpoke"
  | "streak"
  | "seasonal";

export type RomBuzzGiftRarity =
  | "common"
  | "uncommon"
  | "rare"
  | "epic"
  | "legendary"
  | "ultra";

export type RomBuzzGiftPlacement =
  | "reels"
  | "posts"
  | "profile_media"
  | "chat"
  | "buzzpoke"
  | "microbuzz"
  | "match_celebration"
  | "streak"
  | "universal";

export type RomBuzzGiftAssetType =
  | "png"
  | "lottie"
  | "webm"
  | "mp4"
  | "svg"
  | "gif";

export type RomBuzzGiftAnimation =
  | "softFloat"
  | "heartPop"
  | "sparkleRise"
  | "slowSpin"
  | "bounceIn"
  | "glowPulse"
  | "kissBurst"
  | "sway"
  | "zoomPop"
  | "twinkle"
  | "ribbonWave"
  | "lanternGlow"
  | "compassSpin"
  | "capsuleDrop"
  | "candleFlicker"
  | "birdsFlutter"
  | "lockShake"
  | "roseBloom"
  | "crystalShine"
  | "cherryBounce"
  | "bonsaiBreath"
  | "autumnDrift";

export type RomBuzzGift = {
  id: string;
  name: string;
  imageUrl: string;
  category: RomBuzzGiftCategory;
  rarity: RomBuzzGiftRarity;
  priceBC: number;
  animated: boolean;
  animationType: RomBuzzGiftAnimation;
  visualDescription: string;
  emotionalMeaning: string;
  bestPlacement: RomBuzzGiftPlacement;
  appStoreSafetyNote: string;
  designPrompt: string;
  suggestedAssetType: RomBuzzGiftAssetType;
  sortOrder: number;
  enabled: boolean;
  premiumOnly: boolean;
  seasonalOnly: boolean;
  allowedPlacements: RomBuzzGiftPlacement[];
};

const ALL_PLACEMENTS: RomBuzzGiftPlacement[] = [
  "reels",
  "posts",
  "profile_media",
  "chat",
  "buzzpoke",
  "microbuzz",
  "match_celebration",
  "streak",
  "universal",
];

const GIFT_IMAGE_OVERRIDES: Record<string, string> = {
  pink_heart:
    "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780280975/pink_heart_noh9cr.png",
  heart_red:
    "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780280972/heart_red_ngpbdb.png",
  heart_s:
    "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780596844/heart_s_vmawu7.png",
  tea_cup:
    "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780280976/tea_cup_uzcylj.png",
  cherry_love:
    "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780280971/cherry_love_aqjhze.png",
  love_ribbon:
    "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780280975/love_ribbon_jz2fvd.png",
  autumn_love:
    "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780280971/autumn_love_gpynf8.png",
  sparkling_rose:
    "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780280976/sparkling_rose_quomhp.png",
  cuddle_love:
    "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780280972/cuddle_love_zyu5sj.png",
  cute_birds:
    "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780280972/cute_birds_fbarpv.png",
  love_birds:
    "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780280974/love_birds_oup83f.png",
  love_candle:
    "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780280973/love_candle_k9vmex.png",
  candle_light:
    "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780280972/candle_light_cfwxj6.png",
  love_lantern:
    "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780280975/love_lantern_itkmjx.png",
  lantern_blue:
    "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780280973/lantern_blue_tfkhw3.png",
  lock_key:
    "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780281399/lock_key_tq3w5t.png",
  flower_vase:
    "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780280972/flower_vase_srvmoi.png",
  bonsai_love:
    "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780280971/bonsai_love_ony6ei.png",
  rombuzz_love:
    "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780280975/rombuzz_love_mi7ors.png",
  velvet_kiss:
    "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780280977/velvet_kiss_mdi1g6.png",
  love_compass:
    "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780280974/love_compass_nwbcvs.png",
  star_compass:
    "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780596850/Star_Compass_a1rilv.png",
  crystal_swan:
    "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780280972/crystal_swan_kuv8ip.png",
};

const TEMPORARILY_DISABLED_GIFT_IDS = new Set<string>([
  "three_buns",
  "red_rose",
  "love_capsule",
]);

const ROMBUZZ_GIFTS_BASE: RomBuzzGift[] = [
  {
    id: "pink_heart",
    name: "Pink Heart",
    imageUrl:
      "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097131/pink_heart_u0byvz.png",
    category: "romantic",
    rarity: "common",
    priceBC: 5,
    animated: true,
    animationType: "heartPop",
    visualDescription: "Pink heart gift icon with soft romantic styling.",
    emotionalMeaning: "A simple sweet heart reaction.",
    bestPlacement: "universal",
    appStoreSafetyNote: "Safe romantic symbolic gift with no adult or restricted content.",
    designPrompt: "Pink heart romantic gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 1,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "heart_red",
    name: "Red Heart",
    imageUrl:
      "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097124/heart_red_wpi6mn.png",
    category: "romantic",
    rarity: "common",
    priceBC: 8,
    animated: true,
    animationType: "heartPop",
    visualDescription: "Red heart gift icon with a clean romantic look.",
    emotionalMeaning: "A stronger heart reaction.",
    bestPlacement: "universal",
    appStoreSafetyNote: "Safe romantic symbolic gift with no adult or restricted content.",
    designPrompt: "Red heart romantic gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 2,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "heart_s",
    name: "Heart Spark",
    imageUrl:
      
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780596844/heart_s_vmawu7.png",
    category: "romantic",
    rarity: "common",
    priceBC: 9,
    animated: true,
    animationType: "heartPop",
    visualDescription: "Soft heart-style romantic gift icon.",
    emotionalMeaning: "A sweet heart reaction between red heart and tea cup.",
    bestPlacement: "universal",
    appStoreSafetyNote: "Safe romantic symbolic gift with no adult or restricted content.",
    designPrompt: "Soft romantic heart gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 3,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "tea_cup",
    name: "Tea Cup",
    imageUrl:
      "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097135/tea_cup_tddkrl.png",
    category: "sweet",
    rarity: "common",
    priceBC: 10,
    animated: true,
    animationType: "softFloat",
    visualDescription: "Cute romantic tea cup gift icon.",
    emotionalMeaning: "A cozy soft signal.",
    bestPlacement: "chat",
    appStoreSafetyNote: "Safe cozy gift with no adult or restricted content.",
    designPrompt: "Cute romantic tea cup gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 4,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "three_buns",
    name: "Three Buns",
    imageUrl:
      "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097136/three_buns_secb0a.png",
    category: "sweet",
    rarity: "common",
    priceBC: 12,
    animated: true,
    animationType: "bounceIn",
    visualDescription: "Cute dessert-style romantic gift.",
    emotionalMeaning: "A playful sweet reaction.",
    bestPlacement: "posts",
    appStoreSafetyNote: "Safe cute food-style gift with no adult or restricted content.",
    designPrompt: "Cute romantic dessert gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 5,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "cherry_love",
    name: "Cherry Love",
    imageUrl:
      "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097120/cherry_love_l7q10k.png",
    category: "playful",
    rarity: "common",
    priceBC: 15,
    animated: true,
    animationType: "cherryBounce",
    visualDescription: "Cherry heart gift icon.",
    emotionalMeaning: "A playful cute flirt reaction.",
    bestPlacement: "reels",
    appStoreSafetyNote: "Safe playful fruit gift with no adult or restricted content.",
    designPrompt: "Cherry heart romantic gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 6,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "love_ribbon",
    name: "Love Ribbon",
    imageUrl:
      "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097130/love_ribbon_auytjx.png",
    category: "romantic",
    rarity: "common",
    priceBC: 18,
    animated: true,
    animationType: "ribbonWave",
    visualDescription: "Soft ribbon-style romantic gift.",
    emotionalMeaning: "A gentle romantic gesture.",
    bestPlacement: "posts",
    appStoreSafetyNote: "Safe symbolic romantic gift with no adult or restricted content.",
    designPrompt: "Romantic love ribbon gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 7,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "autumn_love",
    name: "Autumn Love",
    imageUrl:
      "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097119/autumn_love_cx8v8h.png",
    category: "seasonal",
    rarity: "common",
    priceBC: 20,
    animated: true,
    animationType: "autumnDrift",
    visualDescription: "Warm autumn-themed romantic gift.",
    emotionalMeaning: "A soft seasonal affection signal.",
    bestPlacement: "universal",
    appStoreSafetyNote: "Safe seasonal romantic gift with no adult or restricted content.",
    designPrompt: "Autumn romantic gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 8,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "red_rose",
    name: "Red Rose",
    imageUrl:
      "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097132/red_rose_uhu0nz.png",
    category: "romantic",
    rarity: "common",
    priceBC: 25,
    animated: true,
    animationType: "roseBloom",
    visualDescription: "Classic red rose romantic gift.",
    emotionalMeaning: "A direct romantic gesture.",
    bestPlacement: "profile_media",
    appStoreSafetyNote: "Safe symbolic romantic flower gift.",
    designPrompt: "Red rose romantic gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 9,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "sparkling_rose",
    name: "Sparkling Rose",
    imageUrl:
      "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097133/sparkling_rose_hj6imz.png",
    category: "romantic",
    rarity: "common",
    priceBC: 30,
    animated: true,
    animationType: "sparkleRise",
    visualDescription: "Sparkling rose romantic gift.",
    emotionalMeaning: "A prettier elevated rose gesture.",
    bestPlacement: "profile_media",
    appStoreSafetyNote: "Safe symbolic flower gift.",
    designPrompt: "Sparkling rose romantic gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 10,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "cuddle_love",
    name: "Cuddle Love",
    imageUrl:
      "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097122/cuddle_love_d0h9yv.png",
    category: "sweet",
    rarity: "uncommon",
    priceBC: 35,
    animated: true,
    animationType: "zoomPop",
    visualDescription: "Soft cuddle-themed romantic gift.",
    emotionalMeaning: "A warm and sweet affection signal.",
    bestPlacement: "chat",
    appStoreSafetyNote: "Safe symbolic cozy gift with no explicit content.",
    designPrompt: "Cute cuddle love gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 11,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "cute_birds",
    name: "Cute Birds",
    imageUrl:
      "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097122/cute_birds_av7c4u.png",
    category: "romantic",
    rarity: "uncommon",
    priceBC: 40,
    animated: true,
    animationType: "birdsFlutter",
    visualDescription: "Cute love bird planter gift.",
    emotionalMeaning: "A gentle romantic togetherness signal.",
    bestPlacement: "universal",
    appStoreSafetyNote: "Safe romantic symbolic bird gift.",
    designPrompt: "Cute love birds romantic gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 12,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "love_birds",
    name: "Love Birds",
    imageUrl:
      "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097127/love_birds_n3dy21.png",
    category: "romantic",
    rarity: "uncommon",
    priceBC: 45,
    animated: true,
    animationType: "birdsFlutter",
    visualDescription: "Two romantic love birds gift.",
    emotionalMeaning: "A stronger togetherness gesture.",
    bestPlacement: "universal",
    appStoreSafetyNote: "Safe symbolic bird gift with no adult or restricted content.",
    designPrompt: "Love birds romantic gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 13,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "love_candle",
    name: "Love Candle",
    imageUrl:
      "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097127/love_candle_mdhh0y.png",
    category: "romantic",
    rarity: "uncommon",
    priceBC: 50,
    animated: true,
    animationType: "candleFlicker",
    visualDescription: "Romantic candle gift with heart styling.",
    emotionalMeaning: "A cozy romantic gesture.",
    bestPlacement: "chat",
    appStoreSafetyNote: "Safe romantic candle symbol with no adult content.",
    designPrompt: "Romantic candle heart gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 14,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "candle_light",
    name: "Candle Light",
    imageUrl:
      "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097119/candle_light_mzncuw.png",
    category: "romantic",
    rarity: "uncommon",
    priceBC: 55,
    animated: true,
    animationType: "lanternGlow",
    visualDescription: "Warm candle light romantic gift.",
    emotionalMeaning: "A gentle cozy affection signal.",
    bestPlacement: "chat",
    appStoreSafetyNote: "Safe symbolic candle gift.",
    designPrompt: "Candle light romantic gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 15,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "love_lantern",
    name: "Love Lantern",
    imageUrl:
      "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097130/love_lantern_hdqnio.png",
    category: "romantic",
    rarity: "uncommon",
    priceBC: 60,
    animated: true,
    animationType: "lanternGlow",
    visualDescription: "Heart lantern romantic gift.",
    emotionalMeaning: "A warm romantic signal.",
    bestPlacement: "reels",
    appStoreSafetyNote: "Safe symbolic lantern gift.",
    designPrompt: "Heart lantern romantic gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 16,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "lantern_blue",
    name: "Blue Lantern",
    imageUrl:
      "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097125/lantern_blue_jv8vhy.png",
    category: "romantic",
    rarity: "uncommon",
    priceBC: 65,
    animated: true,
    animationType: "glowPulse",
    visualDescription: "Premium blue lantern romantic gift.",
    emotionalMeaning: "A calm glowing affection signal.",
    bestPlacement: "reels",
    appStoreSafetyNote: "Safe symbolic lantern gift.",
    designPrompt: "Blue lantern romantic gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 17,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "love_capsule",
    name: "Love Capsule",
    imageUrl:
      "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097128/love_capsule_ta0dbc.png",
    category: "romantic",
    rarity: "rare",
    priceBC: 70,
    animated: true,
    animationType: "capsuleDrop",
    visualDescription: "Love note capsule romantic gift.",
    emotionalMeaning: "A thoughtful message-like affection signal.",
    bestPlacement: "chat",
    appStoreSafetyNote: "Safe symbolic note/capsule gift.",
    designPrompt: "Love note capsule romantic gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 18,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "lock_key",
    name: "Lock Key",
    imageUrl:
      "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097126/lock_key_hyqsfj.png",
    category: "romantic",
    rarity: "rare",
    priceBC: 75,
    animated: true,
    animationType: "lockShake",
    visualDescription: "Heart lock and key romantic gift.",
    emotionalMeaning: "A special trust/connection signal.",
    bestPlacement: "chat",
    appStoreSafetyNote: "Safe symbolic lock/key gift.",
    designPrompt: "Heart lock and key romantic gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 19,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "flower_vase",
    name: "Flower Vase",
    imageUrl:
      "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097124/flower_vase_pxkt3h.png",
    category: "romantic",
    rarity: "rare",
    priceBC: 80,
    animated: true,
    animationType: "sway",
    visualDescription: "Flower vase romantic gift.",
    emotionalMeaning: "A polished thoughtful romantic gesture.",
    bestPlacement: "profile_media",
    appStoreSafetyNote: "Safe symbolic flower gift.",
    designPrompt: "Flower vase romantic gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 20,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "bonsai_love",
    name: "Bonsai Love",
    imageUrl:
      "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097120/bonsai_love_hf11ft.png",
    category: "premium",
    rarity: "rare",
    priceBC: 90,
    animated: true,
    animationType: "bonsaiBreath",
    visualDescription: "Heart bonsai premium romantic gift.",
    emotionalMeaning: "A meaningful growing-connection signal.",
    bestPlacement: "universal",
    appStoreSafetyNote: "Safe symbolic plant/heart gift.",
    designPrompt: "Heart bonsai romantic premium gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 21,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "rombuzz_love",
    name: "RomBuzz Love",
    imageUrl:
      "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097133/rombuzz_love_mjkaak.png",
    category: "premium",
    rarity: "rare",
    priceBC: 100,
    animated: true,
    animationType: "glowPulse",
    visualDescription: "RomBuzz branded love gift.",
    emotionalMeaning: "A stronger app-native love reaction.",
    bestPlacement: "universal",
    appStoreSafetyNote: "Safe branded romantic gift.",
    designPrompt: "RomBuzz love gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 22,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "cake_slice",
    name: "Cake Slice",
    imageUrl:
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780576293/cake_slice_zunipf.png",
    category: "sweet",
    rarity: "rare",
    priceBC: 100,
    animated: true,
    animationType: "softFloat",
    visualDescription: "A sweet cake-slice gift for light romantic moments.",
    emotionalMeaning: "A cute little dessert signal.",
    bestPlacement: "chat",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 23,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "velvet_kiss",
    name: "Velvet Kiss",
    imageUrl:
      "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097137/velvet_kiss_taofc4.png",
    category: "premium",
    rarity: "epic",
    priceBC: 120,
    animated: true,
    animationType: "kissBurst",
    visualDescription: "Premium velvet kiss romantic gift.",
    emotionalMeaning: "A bold romantic signal without explicit content.",
    bestPlacement: "chat",
    appStoreSafetyNote: "Safe stylized romantic gift, not explicit or adult-service oriented.",
    designPrompt: "Velvet kiss romantic premium gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 24,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "pink_rose_premium",
    name: "Pink Rose",
    imageUrl:
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780575934/pink_rose_vng77w.png",
    category: "romantic",
    rarity: "rare",
    priceBC: 120,
    animated: true,
    animationType: "roseBloom",
    visualDescription: "A premium pink rose with soft romantic styling.",
    emotionalMeaning: "A gentle romantic flower gesture.",
    bestPlacement: "universal",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 25,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "star_teddy",
    name: "Star Teddy",
    imageUrl:
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780575893/star_teddy_ppbbo8.png",
    category: "sweet",
    rarity: "rare",
    priceBC: 140,
    animated: true,
    animationType: "twinkle",
    visualDescription: "A teddy bear with a star-themed premium look.",
    emotionalMeaning: "A cozy attention gift with sparkle.",
    bestPlacement: "chat",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 26,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "love_compass",
    name: "Love Compass",
    imageUrl:
      "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097129/love_compass_iinnhg.png",
    category: "premium",
    rarity: "epic",
    priceBC: 150,
    animated: true,
    animationType: "compassSpin",
    visualDescription: "Premium love compass gift.",
    emotionalMeaning: "A destiny/found-you style romantic signal.",
    bestPlacement: "universal",
    appStoreSafetyNote: "Safe symbolic compass gift.",
    designPrompt: "Love compass romantic premium gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 27,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "diamond_ring_classic",
    name: "Diamond Ring Classic",
    imageUrl:
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780575916/diamond_ring__z4udhx.png",
    category: "premium",
    rarity: "rare",
    priceBC: 160,
    animated: true,
    animationType: "crystalShine",
    visualDescription: "A classic diamond ring premium gift.",
    emotionalMeaning: "A special romantic signal.",
    bestPlacement: "universal",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 28,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "star_compass",
    name: "Star Compass",
    imageUrl:
      
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780596850/Star_Compass_a1rilv.png",
    category: "premium",
    rarity: "epic",
    priceBC: 180,
    animated: true,
    animationType: "twinkle",
    visualDescription: "Starlight compass premium gift.",
    emotionalMeaning: "A special destiny-style premium gift.",
    bestPlacement: "universal",
    appStoreSafetyNote: "Safe symbolic compass/star gift.",
    designPrompt: "Starlight compass premium romantic gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 29,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "red_balloon",
    name: "Red Balloon",
    imageUrl:
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780575891/red_balloon_k0qdlx.png",
    category: "playful",
    rarity: "rare",
    priceBC: 180,
    animated: true,
    animationType: "bounceIn",
    visualDescription: "A bright red balloon gift with playful energy.",
    emotionalMeaning: "A cheerful romantic nudge.",
    bestPlacement: "reels",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 30,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "crown_heart",
    name: "Crown Heart",
    imageUrl:
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780596845/crown_heart_exnbyn.png",
    category: "premium",
    rarity: "rare",
    priceBC: 190,
    animated: true,
    animationType: "heartPop",
    visualDescription: "A crown-shaped heart gift with premium romantic styling.",
    emotionalMeaning: "A royal-style romantic attention gift.",
    bestPlacement: "universal",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 31,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "green_teddy",
    name: "Green Teddy",
    imageUrl:
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780575893/green_teddy_qavcx0.png",
    category: "sweet",
    rarity: "rare",
    priceBC: 200,
    animated: true,
    animationType: "softFloat",
    visualDescription: "A soft green teddy gift icon.",
    emotionalMeaning: "A warm comfort-style gift.",
    bestPlacement: "chat",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 32,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "magic_heart",
    name: "Magic Heart",
    imageUrl:
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780575892/magic_heart_xoaaib.png",
    category: "romantic",
    rarity: "rare",
    priceBC: 220,
    animated: true,
    animationType: "heartPop",
    visualDescription: "A glowing magical heart gift.",
    emotionalMeaning: "A stronger heart reaction with sparkle.",
    bestPlacement: "universal",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 33,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "flowers_bouquet",
    name: "Flowers Bouquet",
    imageUrl:
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780575892/flowers_sqyobi.png",
    category: "romantic",
    rarity: "rare",
    priceBC: 240,
    animated: true,
    animationType: "sparkleRise",
    visualDescription: "A premium flower bouquet gift.",
    emotionalMeaning: "A classic romantic appreciation gift.",
    bestPlacement: "profile_media",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 34,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "crystal_swan",
    name: "Crystal Swan",
    imageUrl:
      "https://res.cloudinary.com/drhx99m5f/image/upload/v1778097121/crystal_swan_gzjhyu.png",
    category: "premium",
    rarity: "legendary",
    priceBC: 250,
    animated: true,
    animationType: "crystalShine",
    visualDescription: "Crystal swan premium romantic gift.",
    emotionalMeaning: "A luxury romantic gift for special moments.",
    bestPlacement: "universal",
    appStoreSafetyNote: "Safe symbolic swan/crystal gift.",
    designPrompt: "Crystal swan luxury romantic gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 35,
       enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "blue_teddy",
    name: "Blue Teddy",
    imageUrl:
      
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780596831/Blue_bears_lhldsv.png",
    category: "sweet",
    rarity: "rare",
    priceBC: 260,
    animated: true,
    animationType: "sway",
    visualDescription: "A cute blue teddy bear gift.",
    emotionalMeaning: "A calm soft affection signal.",
    bestPlacement: "chat",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 36,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "small_bird",
    name: "Small Bird",
    imageUrl:
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780575892/small_bird_a0uzlo.png",
    category: "playful",
    rarity: "rare",
    priceBC: 280,
    animated: true,
    animationType: "birdsFlutter",
    visualDescription: "A small bird gift icon with gentle movement.",
    emotionalMeaning: "A sweet playful hello.",
    bestPlacement: "reels",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 37,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "vanilla_cake",
    name: "Vanilla Cake",
    imageUrl:
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780575892/vanilla_cake_ia68pd.png",
    category: "sweet",
    rarity: "epic",
    priceBC: 300,
    animated: true,
    animationType: "bounceIn",
    visualDescription: "A premium vanilla cake gift.",
    emotionalMeaning: "A celebration-style sweet gesture.",
    bestPlacement: "match_celebration",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 38,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "bright_moon",
    name: "Bright Moon",
    imageUrl:
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780575892/bright_moon_pdtns4.png",
    category: "premium",
    rarity: "epic",
    priceBC: 320,
    animated: true,
    animationType: "glowPulse",
    visualDescription: "A bright moon premium romantic gift.",
    emotionalMeaning: "A dreamy late-night attention gift.",
    bestPlacement: "chat",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 39,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "work_teddy",
    name: "Work Teddy",
    imageUrl:
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780575893/work_teddy_fkyics.png",
    category: "funny",
    rarity: "epic",
    priceBC: 340,
    animated: true,
    animationType: "bounceIn",
    visualDescription: "A work-themed teddy bear gift.",
    emotionalMeaning: "A playful support or thinking-of-you gift.",
    bestPlacement: "chat",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 40,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "scarf",
    name: "Cozy Scarf",
    imageUrl:
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780575893/scarf_pqwq01.png",
    category: "sweet",
    rarity: "epic",
    priceBC: 360,
    animated: true,
    animationType: "ribbonWave",
    visualDescription: "A cozy scarf gift icon.",
    emotionalMeaning: "A soft comfort gesture.",
    bestPlacement: "universal",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 41,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "cute_monkey",
    name: "Cute Monkey",
    imageUrl:
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780575891/cute_monkey_ygfnem.png",
    category: "funny",
    rarity: "epic",
    priceBC: 380,
    animated: true,
    animationType: "bounceIn",
    visualDescription: "A cute monkey gift with playful charm.",
    emotionalMeaning: "A funny flirty reaction.",
    bestPlacement: "reels",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 42,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "very_big_cake",
    name: "Very Big Cake",
    imageUrl:
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780575893/very_big_cake_xqm6lz.png",
    category: "celebration",
    rarity: "epic",
    priceBC: 400,
    animated: true,
    animationType: "zoomPop",
    visualDescription: "A big celebration cake gift.",
    emotionalMeaning: "A bold celebration gesture.",
    bestPlacement: "match_celebration",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 43,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "diamond_ring_luxe",
    name: "Diamond Ring Luxe",
    imageUrl:
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780575893/diamond__ring_xj5dgl.png",
    category: "premium",
    rarity: "epic",
    priceBC: 420,
    animated: true,
    animationType: "crystalShine",
    visualDescription: "A luxury diamond ring gift.",
    emotionalMeaning: "A premium romantic signal.",
    bestPlacement: "universal",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 44,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "key_heart",
    name: "Key Heart",
    imageUrl:
      
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780596849/Key_heart_pkfse5.png",
    category: "romantic",
    rarity: "epic",
    priceBC: 440,
    animated: true,
    animationType: "lockShake",
    visualDescription: "A heart key gift with romantic symbolism.",
    emotionalMeaning: "A you-have-my-attention style gift.",
    bestPlacement: "universal",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 45,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "compass_moon",
    name: "Compass Moon",
    imageUrl:
      
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780596838/compass_moon_mktxvn.png",
    category: "premium",
    rarity: "epic",
    priceBC: 460,
    animated: true,
    animationType: "compassSpin",
    visualDescription: "A moon compass gift with dreamy premium styling.",
    emotionalMeaning: "A destiny and direction romantic signal.",
    bestPlacement: "universal",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 46,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "big_diamond",
    name: "Big Diamond",
    imageUrl:
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780575891/big_diamond_u6ep7e.png",
    category: "premium",
    rarity: "epic",
    priceBC: 480,
    animated: true,
    animationType: "crystalShine",
    visualDescription: "A large diamond premium gift.",
    emotionalMeaning: "A shiny high-value attention gift.",
    bestPlacement: "profile_media",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 47,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "real_moon",
    name: "Real Moon",
    imageUrl:
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780576292/real_moon_pu131m.png",
    category: "premium",
    rarity: "epic",
    priceBC: 500,
    animated: true,
    animationType: "glowPulse",
    visualDescription: "A realistic moon-style romantic gift.",
    emotionalMeaning: "A dreamy romantic night signal.",
    bestPlacement: "chat",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 48,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "red_teddy",
    name: "Red Teddy",
    imageUrl:
      
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780596830/red_teddy_cevl4w.png",
    category: "sweet",
    rarity: "epic",
    priceBC: 520,
    animated: true,
    animationType: "heartPop",
    visualDescription: "A red teddy bear romantic gift.",
    emotionalMeaning: "A bold cozy affection gift.",
    bestPlacement: "chat",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 49,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "crystal_rose",
    name: "Crystal Rose",
    imageUrl:
      
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780596834/Crystal_Rose_hjyjqd.png",
    category: "premium",
    rarity: "legendary",
    priceBC: 540,
    animated: true,
    animationType: "crystalShine",
    visualDescription: "A crystal rose premium romantic gift.",
    emotionalMeaning: "A special luxury flower gesture.",
    bestPlacement: "universal",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 50,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "gold_paper_plane",
    name: "Gold Paper Plane",
    imageUrl:
      
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780596829/pink_Paper_Plane_with_gold_vwv0n1.png",
    category: "premium",
    rarity: "legendary",
    priceBC: 560,
    animated: true,
    animationType: "softFloat",
    visualDescription: "A pink paper plane with gold filigree styling.",
    emotionalMeaning: "A charming send-my-heart signal.",
    bestPlacement: "chat",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 51,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "velvet_cup",
    name: "Velvet Cup",
    imageUrl:
      
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780596837/sexy_cup_ju3vhb.png",
    category: "premium",
    rarity: "legendary",
    priceBC: 580,
    animated: true,
    animationType: "candleFlicker",
    visualDescription: "A stylish premium cup gift with romantic flair.",
    emotionalMeaning: "A polished flirty-but-safe gift.",
    bestPlacement: "chat",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 52,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "winged_lips",
    name: "Winged Lips",
    imageUrl:
      
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780596847/wings_lips_bbhxcu.png",
    category: "romantic",
    rarity: "legendary",
    priceBC: 600,
    animated: true,
    animationType: "kissBurst",
    visualDescription: "A stylized winged lips gift.",
    emotionalMeaning: "A bold romantic kiss-style signal without explicit content.",
    bestPlacement: "chat",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 53,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "balloon_golden_lips",
    name: "Golden Lips Balloon",
    imageUrl:
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780596843/balloon_golden_lips_jz7kbv.png",
    category: "romantic",
    rarity: "legendary",
    priceBC: 610,
    animated: true,
    animationType: "kissBurst",
    visualDescription: "A golden lips balloon gift with playful romantic energy.",
    emotionalMeaning: "A bold, flirty, premium attention signal.",
    bestPlacement: "reels",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 54,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "kiss_pop",
    name: "Kiss Pop",
    imageUrl:
      
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780596848/kiss_m6xnyk.png",
    category: "romantic",
    rarity: "legendary",
    priceBC: 620,
    animated: true,
    animationType: "kissBurst",
    visualDescription: "A clean stylized kiss gift icon.",
    emotionalMeaning: "A playful romantic reaction.",
    bestPlacement: "chat",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 55,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "magic_love",
    name: "Magic Love",
    imageUrl:
      
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780596836/magic_love_xlzjv1.png",
    category: "romantic",
    rarity: "legendary",
    priceBC: 640,
    animated: true,
    animationType: "sparkleRise",
    visualDescription: "A magic love gift with premium sparkle.",
    emotionalMeaning: "A special romantic attention gift.",
    bestPlacement: "universal",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 56,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "white_heart_balloon",
    name: "White Heart Balloon",
    imageUrl:
      
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780596841/balloon_heart_white_layonp.png",
    category: "celebration",
    rarity: "legendary",
    priceBC: 660,
    animated: true,
    animationType: "softFloat",
    visualDescription: "A white heart balloon premium gift.",
    emotionalMeaning: "A soft celebration signal.",
    bestPlacement: "match_celebration",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 57,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "magic_cup",
    name: "Magic Cup",
    imageUrl:
      
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780596832/magic_cup_xajxhn.png",
    category: "premium",
    rarity: "legendary",
    priceBC: 680,
    animated: true,
    animationType: "glowPulse",
    visualDescription: "A magic cup premium gift.",
    emotionalMeaning: "A mysterious cozy romantic gesture.",
    bestPlacement: "chat",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 58,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "crystal_gold_music_note",
    name: "Crystal Gold Music Note",
    imageUrl:
      
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780596833/Crystal_Gold_Music_Note_ljdxev.png",
    category: "premium",
    rarity: "legendary",
    priceBC: 700,
    animated: true,
    animationType: "twinkle",
    visualDescription: "A crystal gold music note gift.",
    emotionalMeaning: "A romantic music-inspired signal.",
    bestPlacement: "universal",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 59,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "golden_filigree_key",
    name: "Golden Filigree Key",
    imageUrl:
      
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780596839/Golden_Filigree_Key_u5guag.png",
    category: "premium",
    rarity: "legendary",
    priceBC: 720,
    animated: true,
    animationType: "lockShake",
    visualDescription: "A golden filigree key gift.",
    emotionalMeaning: "A premium key-to-my-attention gesture.",
    bestPlacement: "universal",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 60,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "big_cake",
    name: "Big Cake",
    imageUrl:
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780576282/big_cake_qygctx.png",
    category: "celebration",
    rarity: "legendary",
    priceBC: 740,
    animated: true,
    animationType: "zoomPop",
    visualDescription: "A large premium cake gift.",
    emotionalMeaning: "A big celebration-style gift.",
    bestPlacement: "match_celebration",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 61,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "crystal_perfume_bottle",
    name: "Crystal Perfume Bottle",
    imageUrl:
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780596846/Crystal_Perfume_Botle_j424og.png",
    category: "premium",
    rarity: "legendary",
    priceBC: 740,
    animated: true,
    animationType: "crystalShine",
    visualDescription: "A crystal perfume bottle gift with elegant romantic luxury styling.",
    emotionalMeaning: "A polished premium romantic gesture.",
    bestPlacement: "profile_media",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 62,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "happy_cow",
    name: "Happy Cow",
    imageUrl:
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780576281/happy_cow_j9gjof.png",
    category: "funny",
    rarity: "legendary",
    priceBC: 760,
    animated: true,
    animationType: "bounceIn",
    visualDescription: "A happy cow gift with playful charm.",
    emotionalMeaning: "A funny wholesome reaction.",
    bestPlacement: "reels",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 63,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "red_heart_premium",
    name: "Premium Red Heart",
    imageUrl:
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780575953/red_heart_rwtaoz.png",
    category: "romantic",
    rarity: "legendary",
    priceBC: 780,
    animated: true,
    animationType: "heartPop",
    visualDescription: "A premium red heart gift.",
    emotionalMeaning: "A strong romantic appreciation signal.",
    bestPlacement: "universal",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 64,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "happy_teddy",
    name: "Happy Teddy",
    imageUrl:
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780576233/happy_teddy_amniiy.png",
    category: "sweet",
    rarity: "legendary",
    priceBC: 800,
    animated: true,
    animationType: "bounceIn",
    visualDescription: "A happy teddy bear premium gift.",
    emotionalMeaning: "A warm happy affection gift.",
    bestPlacement: "chat",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 65,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "red_lips",
    name: "Red Lips",
    imageUrl:
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780576281/red_lips_onusi5.png",
    category: "romantic",
    rarity: "legendary",
    priceBC: 820,
    animated: true,
    animationType: "kissBurst",
    visualDescription: "A stylized red lips gift.",
    emotionalMeaning: "A bold kiss-style romantic signal.",
    bestPlacement: "chat",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 66,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "diamond_ring_spark",
    name: "Diamond Ring Spark",
    imageUrl:
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780576281/diamond_ring_ftc468.jpg",
    category: "premium",
    rarity: "ultra",
    priceBC: 840,
    animated: true,
    animationType: "crystalShine",
    visualDescription: "A sparkling diamond ring ultra gift.",
    emotionalMeaning: "A very high-value romantic gesture.",
    bestPlacement: "universal",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 67,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "hug_teddy",
    name: "Hug Teddy",
    imageUrl:
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780576281/hug_teddy_umuydb.png",
    category: "sweet",
    rarity: "ultra",
    priceBC: 860,
    animated: true,
    animationType: "heartPop",
    visualDescription: "A teddy bear hug gift.",
    emotionalMeaning: "A warm emotional affection gift.",
    bestPlacement: "chat",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 68,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "cute_teddy",
    name: "Cute Teddy",
    imageUrl:
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780576282/cute_teddy_mmvfny.png",
    category: "sweet",
    rarity: "ultra",
    priceBC: 880,
    animated: true,
    animationType: "sway",
    visualDescription: "A cute teddy bear ultra gift.",
    emotionalMeaning: "A soft premium affection signal.",
    bestPlacement: "chat",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 69,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "sing_teddy",
    name: "Sing Teddy",
    imageUrl:
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780576281/sing_teddy_sscobz.png",
    category: "playful",
    rarity: "ultra",
    priceBC: 900,
    animated: true,
    animationType: "twinkle",
    visualDescription: "A singing teddy bear gift.",
    emotionalMeaning: "A playful music-style romantic attention gift.",
    bestPlacement: "chat",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 70,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "rain_teddy",
    name: "Rain Teddy",
    imageUrl:
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780576282/rain_teddy_m2kfma.png",
    category: "sweet",
    rarity: "ultra",
    priceBC: 930,
    animated: true,
    animationType: "softFloat",
    visualDescription: "A rain-themed teddy bear gift.",
    emotionalMeaning: "A comfort gift for soft emotional moments.",
    bestPlacement: "chat",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 71,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "plant_teddy",
    name: "Plant Teddy",
    imageUrl:
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780576282/plant_teddy_jk85jr.png",
    category: "sweet",
    rarity: "ultra",
    priceBC: 960,
    animated: true,
    animationType: "bonsaiBreath",
    visualDescription: "A teddy bear with plant-themed styling.",
    emotionalMeaning: "A gentle growing-connection gesture.",
    bestPlacement: "universal",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 72,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  },
  {
    id: "happy_bear",
    name: "Happy Bear",
    imageUrl:
      "https://res.cloudinary.com/dn3mhtbb3/image/upload/v1780576282/happy_bear_xkmpyp.png",
    category: "exclusive",
    rarity: "ultra",
    priceBC: 1000,
    animated: true,
    animationType: "glowPulse",
    visualDescription: "A premium happy bear ultra gift.",
    emotionalMeaning: "A top-tier warm romantic attention gift.",
    bestPlacement: "universal",
    appStoreSafetyNote: "Safe romantic, playful, or symbolic gift with no adult or restricted content.",
    designPrompt: "Premium 3D RomBuzz gift icon, transparent background, no text.",
    suggestedAssetType: "png",
    sortOrder: 73,
    enabled: true,
    premiumOnly: false,
    seasonalOnly: false,
    allowedPlacements: ALL_PLACEMENTS,
  }
];

export const ROMBUZZ_GIFTS: RomBuzzGift[] = ROMBUZZ_GIFTS_BASE.map((gift) => ({
  ...gift,
  imageUrl: GIFT_IMAGE_OVERRIDES[gift.id] || gift.imageUrl,
  enabled: TEMPORARILY_DISABLED_GIFT_IDS.has(gift.id) ? false : gift.enabled,
}));

export function getGiftById(id: string) {
  return ROMBUZZ_GIFTS.find((gift) => gift.id === id) || null;
}

export function getGiftsByCategory(category: RomBuzzGiftCategory) {
  return ROMBUZZ_GIFTS.filter(
    (gift) => gift.enabled && gift.category === category
  ).sort((a, b) => a.sortOrder - b.sortOrder);
}

export function getAnimatedGifts() {
  return ROMBUZZ_GIFTS.filter((gift) => gift.enabled && gift.animated).sort(
    (a, b) => a.sortOrder - b.sortOrder
  );
}

export function getGiftsByPlacement(placement: RomBuzzGiftPlacement) {
  return ROMBUZZ_GIFTS.filter((gift) => {
    if (!gift.enabled) return false;
    if (gift.allowedPlacements.includes("universal")) return true;
    return gift.allowedPlacements.includes(placement);
  }).sort((a, b) => a.sortOrder - b.sortOrder);
}

export function getGiftsForPlacement(placement: RomBuzzGiftPlacement) {
  return getGiftsByPlacement(placement);
}

export function getGiftPrice(id: string) {
  return getGiftById(id)?.priceBC ?? 0;
}

export function isGiftAnimated(id: string) {
  return Boolean(getGiftById(id)?.animated);
}