/** Theme-aware composer styles for the mobile chat window. */
import { StyleSheet } from "react-native";
import { RBZFont } from "@/src/design/rombuzzTypography";
import type { RomBuzzColors } from "@/src/design/rombuzzTheme";

export function createComposerStyles(
  colors: RomBuzzColors,
  BUBBLE_MAX_W: number,
) {
  return StyleSheet.create({
    composer: {
      backgroundColor: colors.background,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.border,
      paddingHorizontal: 12,
      paddingTop: 10,
      paddingBottom: 0,
      flexShrink: 0,
      overflow: "visible",
    },
    editChip: {
      alignSelf: "flex-start",
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      backgroundColor: colors.brand,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 999,
      marginBottom: 8,
    },
    editChipText: {
      color: colors.white,
      fontFamily: RBZFont.extraBold,
      fontSize: 12,
    },
    replyComposerBar: {
      flexDirection: "row",
      alignItems: "stretch",
      gap: 10,
      backgroundColor: colors.surfaceMuted,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 16,
      paddingHorizontal: 10,
      paddingVertical: 10,
      marginBottom: 8,
    },
    replyComposerAccent: {
      width: 4,
      alignSelf: "stretch",
      borderRadius: 999,
      backgroundColor: colors.brand,
    },
    replyComposerBody: {
      flex: 1,
      minWidth: 0,
      justifyContent: "center",
    },
    replyComposerLabel: {
      fontSize: 11,
      lineHeight: 14,
      fontFamily: RBZFont.extraBold,
      color: colors.brand,
    },
    replyComposerText: {
      marginTop: 3,
      fontSize: 12,
      lineHeight: 16,
      fontFamily: RBZFont.bold,
      color: colors.text,
    },
    replyComposerClose: {
      width: 24,
      height: 24,
      borderRadius: 999,
      alignItems: "center",
      justifyContent: "center",
    },
    composerRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      minHeight: 44,
    },
    inputWrap: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      gap: 7,
    },
    inputWrapExpanded: {
      flex: 1,
    },
    attachBtn: {
      width: 40,
      height: 40,
      borderRadius: 999,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.brandSoft,
      borderWidth: 1,
      borderColor: colors.brandSoft,
    },
    cameraBtn: {
      width: 40,
      height: 40,
      borderRadius: 999,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.brandSoft,
      borderWidth: 1,
      borderColor: colors.brandSoft,
    },
    voiceActionSlot: {
      width: 40,
      height: 40,
      borderRadius: 999,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.brandSoft,
      borderWidth: 1,
      borderColor: colors.brandSoft,
      overflow: "hidden",
    },
    input: {
      flex: 1,
      minHeight: 44,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 12,
      paddingTop: 11,
      paddingBottom: 11,
      color: colors.text,
      backgroundColor: colors.surfaceMuted,
      fontSize: 14,
      fontFamily: RBZFont.medium,
    },
    inputMultiline: {
      maxHeight: 120,
    },
    sendBtn: {
      width: 44,
      height: 44,
      borderRadius: 16,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.brand,
    },
    expandActionsBtn: {
      width: 40,
      height: 40,
      borderRadius: 999,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.brandSoft,
      borderWidth: 1,
      borderColor: "rgba(0,0,0,0.08)",
    },
    inlineActionsRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingRight: 4,
    },
    inlineActionBtn: {
      width: 40,
      height: 40,
      borderRadius: 999,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.brandSoft,
      borderWidth: 1,
      borderColor: colors.brandSoft,
    },
    inlineVoiceWrap: {
      width: 40,
      height: 40,
      borderRadius: 999,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.brandSoft,
      borderWidth: 1,
      borderColor: colors.brandSoft,
      overflow: "hidden",
    },
  });
}
